version: '3.8'
services:
  RadioMasterWeb:
    image: radiomasterphp
    build: ./web
    volumes:
      - ./web:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8000:80

#  RadioMasterDb:
#